<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        Product::insert([
            [
                'seller_id' => rand(1, 10),
                'category_id' => 1,
                'name' => 'আলু',
                'description' => 'আলু একটি বহুল ব্যবহৃত সবজি যা প্রতিদিনের রান্নায় ব্যবহার করা হয়। এটি ভাজি, ভর্তা, কারি ইত্যাদি বিভিন্ন রেসিপিতে ব্যবহৃত হয় এবং পুষ্টিগুণেও সমৃদ্ধ।',
                'price' => 25,
                'stock_quantity' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1590165482129-1b8b27698780?q=80&w=627&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => rand(1, 10),
                'category_id' => 1,
                'name' => 'টমেটো',
                'description' => 'টমেটো রান্নায় রঙ এবং স্বাদ আনতে ব্যবহৃত একটি অতি প্রয়োজনীয় সবজি। এটি ভিটামিন সি এবং অ্যান্টিঅক্সিডেন্টে ভরপুর, যা শরীরের রোগ প্রতিরোধ ক্ষমতা বাড়ায়।',
                'price' => 40,
                'stock_quantity' => 60,
                'image_url' => 'https://images.unsplash.com/photo-1524593166156-312f362cada0?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => rand(1, 10),
                'category_id' => 1,
                'name' => 'বেগুন',
                'description' => 'বেগুন একটি সহজলভ্য সবজি যা ভাজি, ভর্তা এবং দম পদে বহুল ব্যবহৃত হয়। এটি আয়রন ও ফাইবারে সমৃদ্ধ এবং পেটের জন্য উপকারী।',
                'price' => 35,
                'stock_quantity' => 80,
                'image_url' => 'https://images.unsplash.com/photo-1613881553903-4543f5f2cac9?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => rand(1, 10),
                'category_id' => 1,
                'name' => 'শসা',
                'description' => 'শসা একটি জলীয় উপাদান সমৃদ্ধ সবজি যা সালাদে সবচেয়ে বেশি ব্যবহৃত হয়। এটি শরীর ঠান্ডা রাখে এবং ত্বকের জন্য উপকারী।',
                'price' => 30,
                'stock_quantity' => 90,
                'image_url' => 'https://images.unsplash.com/photo-1627981906592-ae3f0ee9486d?q=80&w=694&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => rand(1, 10),
                'category_id' => 1,
                'name' => 'লাউ',
                'description' => 'লাউ হালকা ও সহজ পাচ্য একটি সবজি, যা গরমের দিনে শরীর ঠান্ডা রাখতে সাহায্য করে। এটি উচ্চ ফাইবার এবং ভিটামিন সমৃদ্ধ।',
                'price' => 45,
                'stock_quantity' => 70,
                'image_url' => 'https://lh4.googleusercontent.com/proxy/-4492-p-M3OYVZkPwYtW_MjDhVIWKI35qZHgqn7gz9wrNG84jektNMBHok9dus-LzqYguzfQUUZRleh2Pbu2qpYRZew9MocQgHv_lLuQ7VuLr2Gmu3mmU2L7i7YiRFPj',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => rand(1, 10),
                'category_id' => 1,
                'name' => 'পুঁই শাক',
                'description' => 'পুঁই শাক একটি সবুজ পাতাযুক্ত সবজি যা আয়রন ও ক্যালসিয়ামে সমৃদ্ধ। এটি ভাজি, ডাল ও ভর্তায় ব্যবহৃত হয় এবং রক্তস্বল্পতা প্রতিরোধে কার্যকর।',
                'price' => 20,
                'stock_quantity' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => rand(1, 10),
                'category_id' => 1,
                'name' => 'করলা',
                'description' => 'করলা একটি তিক্ত স্বাদের কিন্তু পুষ্টিকর সবজি। এটি ডায়াবেটিস নিয়ন্ত্রণে সাহায্য করে এবং হজম শক্তি বাড়ায়।',
                'price' => 28,
                'stock_quantity' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1739903760973-4731a8e79a03?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => rand(1, 10),
                'category_id' => 1,
                'name' => 'মুলা',
                'description' => 'মুলা একটি রসালো শীতকালীন সবজি যা সালাদ ও রান্নায় ব্যবহার করা হয়। এটি হজমে সহায়ক এবং লিভারের জন্য উপকারী।',
                'price' => 22,
                'stock_quantity' => 55,
                'image_url' => 'https://images.unsplash.com/photo-1585369496178-144fd937f249?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => rand(1, 10),
                'category_id' => 1,
                'name' => 'ঢেঁড়স',
                'description' => 'ঢেঁড়স একটি পিচ্ছিল ধরনের সবজি, যা ভাজি ও কারিতে ব্যবহৃত হয়। এটি রক্তে চিনি নিয়ন্ত্রণে সাহায্য করে এবং পেট পরিষ্কার রাখে।',
                'price' => 38,
                'stock_quantity' => 65,
                'image_url' => 'https://images.unsplash.com/photo-1664289242854-e99d345cfa92?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => rand(1, 10),
                'category_id' => 1,
                'name' => 'শিম',
                'description' => 'শিম একটি মৌসুমী সবজি, যা তরকারি এবং ভাজিতে ব্যবহৃত হয়। এতে রয়েছে প্রোটিন, ভিটামিন ও মিনারেল, যা শরীরের জন্য খুব উপকারী।',
                'price' => 32,
                'stock_quantity' => 75,
                'image_url' => 'https://images.unsplash.com/photo-1560252030-9fc63cb78dac?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'seller_id' => 3,
                'category_id' => 2,
                'name' => 'আম',
                'description' => 'আম বাংলাদেশের জাতীয় ফল এবং সবচেয়ে জনপ্রিয় ফল। এটি রসালো, মিষ্টি এবং বিভিন্ন ধরনের ভিটামিন ও মিনারেলে ভরপুর।',
                'price' => 120,
                'stock_quantity' => 150,
                'image_url' => 'https://images.unsplash.com/photo-1669207334420-66d0e3450283?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 7,
                'category_id' => 2,
                'name' => 'কলা',
                'description' => 'কলা একটি পুষ্টিকর ফল যা শক্তি প্রদানকারী হিসেবে পরিচিত। এতে পটাশিয়াম, ভিটামিন বি৬ এবং ফাইবার থাকে।',
                'price' => 45,
                'stock_quantity' => 200,
                'image_url' => 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmFuYW5hc3xlbnwwfHwwfHx8MA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'category_id' => 2,
                'name' => 'পেঁপে',
                'description' => 'পেঁপে একটি সুস্বাদু ও স্বাস্থ্যকর ফল যা হজমে সাহায্য করে। এতে পাপাইন নামক এনজাইম থাকে যা প্রোটিন ভাঙ্গতে সহায়তা করে।',
                'price' => 35,
                'stock_quantity' => 90,
                'image_url' => 'https://images.unsplash.com/photo-1617112848923-cc2234396a8d?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 5,
                'category_id' => 2,
                'name' => 'লিচু',
                'description' => 'লিচু একটি মৌসুমী ফল যা গ্রীষ্মকালে পাওয়া যায়। এটি মিষ্টি স্বাদের এবং ভিটামিন সি সমৃদ্ধ।',
                'price' => 180,
                'stock_quantity' => 60,
                'image_url' => 'https://plus.unsplash.com/premium_photo-1722961405963-68d07a1fb633?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 9,
                'category_id' => 2,
                'name' => 'কমলা',
                'description' => 'কমলা ভিটামিন সি এর একটি উৎকৃষ্ট উৎস। এটি ঠাণ্ডা-কাশি প্রতিরোধে সাহায্য করে এবং রোগ প্রতিরোধ ক্ষমতা বাড়ায়।',
                'price' => 80,
                'stock_quantity' => 120,
                'image_url' => 'https://images.unsplash.com/photo-1603455907355-097260ccc037?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 1,
                'category_id' => 2,
                'name' => 'আনারস',
                'description' => 'আনারস একটি ট্রপিক্যাল ফল যা মিষ্টি ও টকমিষ্টি স্বাদের। এতে ব্রোমেলিন নামক এনজাইম থাকে যা হজমে সহায়ক।',
                'price' => 65,
                'stock_quantity' => 70,
                'image_url' => 'https://images.unsplash.com/photo-1621409443141-46c42dc0afb5?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 4,
                'category_id' => 2,
                'name' => 'জাম্বুরা',
                'description' => 'জাম্বুরা একটি বড় সাইট্রাস ফল যা ভিটামিন সি সমৃদ্ধ। এটি রক্ত পরিষ্কারক এবং ওজন কমাতে সাহায্য করে।',
                'price' => 55,
                'stock_quantity' => 85,
                'image_url' => 'https://images.unsplash.com/photo-1662267627145-21f10079c48d?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 8,
                'category_id' => 2,
                'name' => 'কাঁঠাল',
                'description' => 'কাঁঠাল বাংলাদেশের জাতীয় ফলগুলির মধ্যে একটি এবং এটি আকারে বড়। এটি শক্তিদায়ক এবং বিভিন্ন পুষ্টিগুণে ভরপুর।',
                'price' => 95,
                'stock_quantity' => 40,
                'image_url' => 'https://static.toiimg.com/photo/78352922.cms',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 6,
                'category_id' => 2,
                'name' => 'তরমুজ',
                'description' => 'তরমুজ একটি জলযুক্ত ফল যা গ্রীষ্মকালে শরীর ঠাণ্ডা রাখে। এতে লাইকোপিন থাকে যা হৃদরোগ প্রতিরোধে সাহায্য করে।',
                'price' => 40,
                'stock_quantity' => 110,
                'image_url' => 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 10,
                'category_id' => 2,
                'name' => 'স্ট্রবেরি',
                'description' => 'স্ট্রবেরি একটি সুস্বাদু ও পুষ্টিকর ফল যা অ্যান্টিঅক্সিডেন্টে ভরপুর। এটি ত্বকের জন্য খুব উপকারী।',
                'price' => 250,
                'stock_quantity' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1587393855524-087f83d95bc9?q=80&w=760&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'category_id' => 3,
                'name' => 'গরুর মাংস',
                'description' => 'তাজা গরুর মাংস, প্রোটিন ও আয়রনের উৎকৃষ্ট উৎস। রান্নার জন্য উপযুক্ত এবং স্বাস্থ্যকর।',
                'price' => 650,
                'stock_quantity' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1690983321750-ad6f6d59a84b?q=80&w=692&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 5,
                'category_id' => 3,
                'name' => 'খাসির মাংস',
                'description' => 'তাজা খাসির মাংস, বিশেষ করে বিরিয়ানি ও কারি রান্নার জন্য আদর্শ। কম চর্বিযুক্ত অংশ উপলব্ধ।',
                'price' => 750,
                'stock_quantity' => 35,
                'image_url' => 'https://images.unsplash.com/photo-1723893905879-0e309c2a8e06?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 1,
                'category_id' => 3,
                'name' => 'মুরগির বুকের মাংস',
                'description' => 'তাজা মুরগির বুকের মাংস, প্রোটিন সমৃদ্ধ ও কম চর্বিযুক্ত। স্বাস্থ্য সচেতনদের জন্য উত্তম পছন্দ।',
                'price' => 350,
                'stock_quantity' => 80,
                'image_url' => 'https://images.unsplash.com/photo-1672787153652-b3b9d92f3e8c?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 7,
                'category_id' => 3,
                'name' => 'হাঁসের মাংস',
                'description' => 'তাজা হাঁসের মাংস, স্বাদে ভিন্নতা আনার জন্য চমৎকার। বিভিন্ন রকমের রেসিপিতে ব্যবহার করা যায়।',
                'price' => 550,
                'stock_quantity' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1642102904019-2eb4c4d2b492?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'category_id' => 3,
                'name' => 'গরুর কলিজা',
                'description' => 'তাজা গরুর কলিজা, আয়রন ও ভিটামিন এ সমৃদ্ধ। ভুনা বা ভাজি করে খাওয়ার জন্য উপযোগী।',
                'price' => 400,
                'stock_quantity' => 30,
                'image_url' => 'https://www.heritagebd71.com/wp-content/uploads/2023/01/IMG_20230105_140658_579-min.jpg',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 4,
                'category_id' => 3,
                'name' => 'মুরগির সম্পূর্ণ',
                'description' => 'তাজা সম্পূর্ণ মুরগি, বিভিন্ন রান্নার জন্য উপযুক্ত। ফার্মে পালিত, স্বাস্থ্যসম্মতভাবে প্রস্তুতকৃত।',
                'price' => 280,
                'stock_quantity' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 1,
                'category_id' => 4,
                'name' => 'ইলিশ মাছ',
                'description' => 'তাজা পদ্মা নদীর ইলিশ মাছ, বাংলাদেশের জাতীয় মাছ। ভাপা, ভাজি বা সর্ষে ইলিশ রান্নার জন্য উপযুক্ত।',
                'price' => 1200,
                'stock_quantity' => 20,
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/d/d3/BHilsa123.jpg',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'category_id' => 4,
                'name' => 'রুই মাছ',
                'description' => 'প্রোটিন সমৃদ্ধ তাজা রুই মাছ। মাছ ঝোল বা ভাজি করার জন্য আদর্শ।',
                'price' => 350,
                'stock_quantity' => 50,
                'image_url' => 'https://img500.exportersindia.com/product_images/bc-500/dir_179/5340732/rohu-fish-1514783801-3552179.jpeg',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 5,
                'category_id' => 4,
                'name' => 'পাঙ্গাশ মাছ',
                'description' => 'কম দামে উচ্চ পুষ্টিগুণ সম্পন্ন তাজা পাঙ্গাশ মাছ। ফ্রাই বা কারি রান্নার জন্য উত্তম।',
                'price' => 200,
                'stock_quantity' => 70,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlz1SyQnhGpQPYNDPEIFY_IMiQfwIlpDe--w&s',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'category_id' => 4,
                'name' => 'চিংড়ি',
                'description' => 'তাজা পানি চিংড়ি, মালাইকারি বা ভাজি করার জন্য উপযোগী।',
                'price' => 600,
                'stock_quantity' => 30,
                'image_url' => 'https://plus.unsplash.com/premium_photo-1674498270530-194351b7af3e?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 4,
                'category_id' => 4,
                'name' => 'টেংরা মাছ',
                'description' => 'ছোট আকারের কিন্তু স্বাদে অতুলনীয় টেংরা মাছ। ঝোলে ব্যবহৃত হয়।',
                'price' => 250,
                'stock_quantity' => 40,
                'image_url' => 'https://api.globy.com/public/market/6526c425801bd40047b81a99/photos/6526c425801bd40047b81aa2/6526c425801bd40047b81aa2_lg.webp',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 6,
                'category_id' => 4,
                'name' => 'কাতলা মাছ',
                'description' => 'মাংসল কাতলা মাছ, কোরমা বা ঝাল রান্নার জন্য চমৎকার।',
                'price' => 400,
                'stock_quantity' => 35,
                'image_url' => 'https://www.bazaarkgp.com/product_image/11744906013.jpg',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 1,
                'category_id' => 5,
                'name' => 'তাজা দুধ',
                'description' => 'গরুর খামার থেকে সংগ্রহকৃত তাজা দুধ, ক্যালসিয়াম ও প্রোটিন সমৃদ্ধ। চা, মিষ্টি বা সরাসরি পান করার জন্য উত্তম।',
                'price' => 70,
                'stock_quantity' => 100,
                'image_url' => 'https://plus.unsplash.com/premium_photo-1694481099872-29a6ece2672c?q=80&w=688&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'category_id' => 5,
                'name' => 'দই',
                'description' => 'ঘরে তৈরি প্রোবায়োটিক সমৃদ্ধ দই, হজমশক্তি বৃদ্ধি করে ও স্বাস্থ্যের জন্য উপকারী।',
                'price' => 120,
                'stock_quantity' => 60,
                'image_url' => 'https://images.unsplash.com/photo-1571212515416-fef01fc43637?q=80&w=682&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'category_id' => 5,
                'name' => 'পনির',
                'description' => 'তাজা গরুর দুধ থেকে তৈরি পনির, সালাদ বা ভাজি করার জন্য উপযুক্ত। প্রোটিনের ভাল উৎস।',
                'price' => 250,
                'stock_quantity' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1683314573422-649a3c6ad784?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 4,
                'category_id' => 5,
                'name' => 'মাখন',
                'description' => 'শুদ্ধ গরুর দুধ থেকে তৈরি মাখন, রান্না বা ব্রেডের সাথে খাওয়ার জন্য আদর্শ।',
                'price' => 350,
                'stock_quantity' => 30,
                'image_url' => 'https://plus.unsplash.com/premium_photo-1700612685421-7e95b4a857dd?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 5,
                'category_id' => 5,
                'name' => 'ঘি',
                'description' => 'পরিবারের ঐতিহ্যবাহী পদ্ধতিতে তৈরি খাঁটি ঘি, স্বাদ ও গন্ধে অতুলনীয়।',
                'price' => 500,
                'stock_quantity' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1573812461383-e5f8b759d12e?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 6,
                'category_id' => 5,
                'name' => 'আইসক্রিম',
                'description' => 'তাজা দুধ ও প্রাকৃতিক উপাদানে তৈরি ভ্যানিলা ফ্লেভারের আইসক্রিম।',
                'price' => 150,
                'stock_quantity' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?q=80&w=708&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 1,
                'category_id' => 6,
                'name' => 'জিরা',
                'description' => 'উচ্চমানের জিরা গুঁড়া, রান্নার স্বাদ ও গন্ধ বৃদ্ধি করে। বিরিয়ানি ও তরকারিতে ব্যবহার করা হয়।',
                'price' => 180,
                'stock_quantity' => 120,
                'image_url' => 'https://plus.unsplash.com/premium_photo-1725646220374-cef10998bd8b?q=80&w=873&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'category_id' => 6,
                'name' => 'ধনিয়া গুঁড়া',
                'description' => 'তাজা ধনিয়া গুঁড়া, মসলা হিসেবে সব ধরনের রান্নায় ব্যবহার করা যায়।',
                'price' => 150,
                'stock_quantity' => 150,
                'image_url' => 'https://sryshayagroup.com/product-images/Dry%20Coriander%20Powder%20PRIME.png',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'category_id' => 6,
                'name' => 'হলুদ গুঁড়া',
                'description' => 'প্রাকৃতিক হলুদ গুঁড়া, রান্নায় রং ও স্বাদ বাড়াতে ব্যবহার করা হয়। এন্টি-ইনফ্লেমেটরি গুণাগুণ রয়েছে।',
                'price' => 200,
                'stock_quantity' => 200,
                'image_url' => 'https://img.drz.lazcdn.com/static/bd/p/eefbeb06b3df3287f8c5f2d3ed98a2a3.jpg_720x720q80.jpg',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 4,
                'category_id' => 6,
                'name' => 'মরিচ গুঁড়া',
                'description' => 'তীক্ষ্ণ স্বাদের লাল মরিচ গুঁড়া, রান্নায় ঝাল বাড়াতে ব্যবহার করা হয়।',
                'price' => 220,
                'stock_quantity' => 100,
                'image_url' => 'https://onaturalbd.com/wp-content/uploads/2022/02/%E0%A6%AE%E0%A6%B0%E0%A6%BF%E0%A6%9A%E0%A7%87%E0%A6%B0-%E0%A6%97%E0%A7%81%E0%A6%A1%E0%A6%BC%E0%A6%BE-1.jpg',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 5,
                'category_id' => 6,
                'name' => 'গরম মসলা',
                'description' => 'বিভিন্ন মসলার মিশ্রণ, বিরিয়ানি ও তরকারির স্বাদ বাড়াতে ব্যবহার করা হয়।',
                'price' => 250,
                'stock_quantity' => 80,
                'image_url' => 'https://images.unsplash.com/photo-1633881614907-8587c9b93c2f?q=80&w=871&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 6,
                'category_id' => 6,
                'name' => 'দারুচিনি',
                'description' => 'উচ্চমানের দারুচিনি, মিষ্টান্ন ও মাংস রান্নায় ব্যবহার করা হয়। রক্তে শর্করা নিয়ন্ত্রণে সাহায্য করে।',
                'price' => 300,
                'stock_quantity' => 60,
                'image_url' => 'https://images.unsplash.com/photo-1601379758962-cadba22b1e3a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 1,
                'category_id' => 7,
                'name' => 'চানাচুর',
                'description' => 'ক্রিস্পি চানাচুর, স্ন্যাক্স হিসেবে জনপ্রিয়। বিভিন্ন ফ্লেভারে পাওয়া যায়।',
                'price' => 20,
                'stock_quantity' => 200,
                'image_url' => 'https://img.freepik.com/premium-photo/chanachur-mix-with-nut-white-background-chanachur-food_732066-19.jpg',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'category_id' => 7,
                'name' => 'জিলাপি',
                'description' => 'তাজা ভাজা জিলাপি, মিষ্টি স্ন্যাক্স হিসেবে সকালে বা সন্ধ্যায় খাওয়া হয়।',
                'price' => 150,
                'stock_quantity' => 50,
                'image_url' => 'https://static.toiimg.com/thumb/53099699.cms?imgsize=182393&width=800&height=800',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'category_id' => 7,
                'name' => 'সমুচা',
                'description' => 'ক্রিস্পি সমুচা, ভর্তা বা কিমা দিয়ে তৈরি। টি-টাইম স্ন্যাক্স হিসেবে আদর্শ।',
                'price' => 10,
                'stock_quantity' => 300,
                'image_url' => 'https://b.zmtcdn.com/data/pictures/0/19091430/0ef36e1bd5f5b0dd84c7c4da3ea2bcf2_featured_v2.jpg',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 4,
                'category_id' => 7,
                'name' => 'মুরি',
                'description' => 'তাজা ভাজা মুরি, জর্দা বা চিনি দিয়ে মাখিয়ে খাওয়া হয়।',
                'price' => 80,
                'stock_quantity' => 150,
                'image_url' => 'https://m.media-amazon.com/images/I/51lR5aYJ1KL._UF1000,1000_QL80_.jpg',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 5,
                'category_id' => 7,
                'name' => 'সিঙ্গারা',
                'description' => 'ক্রিস্পি সিঙ্গারা, আলু বা মাংসের ফিলিং দিয়ে তৈরি। জনপ্রিয় সকালের নাস্তা।',
                'price' => 15,
                'stock_quantity' => 250,
                'image_url' => 'https://i.ytimg.com/vi/atCrB22qM-Q/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBJdKB6eeGqm3pZAorikMfZrHTTmw',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 6,
                'category_id' => 7,
                'name' => 'বিস্কুট',
                'description' => 'বিভিন্ন ফ্লেভারের বিস্কুট, চায়ের সাথে স্ন্যাক্স হিসেবে খাওয়া হয়।',
                'price' => 120,
                'stock_quantity' => 180,
                'image_url' => 'https://images.unsplash.com/photo-1590400926865-1c70a2586bb5?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 1,
                'category_id' => 8,
                'name' => 'পাউরুটি',
                'description' => 'তাজা সাদা পাউরুটি, সকালের নাস্তা বা স্যান্ডউইচ বানানোর জন্য আদর্শ।',
                'price' => 45,
                'stock_quantity' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1598373182133-52452f7691ef?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'category_id' => 8,
                'name' => 'ব্রেড স্টিক',
                'description' => 'ক্রিস্পি ব্রেড স্টিক, স্যুপ বা চায়ের সাথে খাওয়ার জন্য উপযুক্ত।',
                'price' => 30,
                'stock_quantity' => 150,
                'image_url' => 'https://images.unsplash.com/photo-1559811814-e2c57b5e69df?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'category_id' => 8,
                'name' => 'কেক স্লাইস',
                'description' => 'নরম ও স্পঞ্জি কেক স্লাইস, বিভিন্ন ফ্লেভারে পাওয়া যায়।',
                'price' => 60,
                'stock_quantity' => 80,
                'image_url' => 'https://images.unsplash.com/photo-1685957652870-d56b0e5bea52?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 4,
                'category_id' => 8,
                'name' => 'বিস্কুট',
                'description' => 'ক্রিস্পি বিস্কুট, চায়ের সাথে স্ন্যাক্স হিসেবে জনপ্রিয়।',
                'price' => 25,
                'stock_quantity' => 200,
                'image_url' => 'https://images.unsplash.com/photo-1524566238554-4f7b8ee00582?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 5,
                'category_id' => 8,
                'name' => 'ডোনাট',
                'description' => 'মিষ্টি ডোনাট, বিভিন্ন টপিংস সহ পাওয়া যায়।',
                'price' => 40,
                'stock_quantity' => 120,
                'image_url' => 'https://images.unsplash.com/photo-1533137015-38dbe301e281?q=80&w=891&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 6,
                'category_id' => 8,
                'name' => 'পেস্ট্রি',
                'description' => 'নরম পেস্ট্রি, বিভিন্ন ফিলিং সহ পাওয়া যায়।',
                'price' => 35,
                'stock_quantity' => 90,
                'image_url' => 'https://krbakes.com/cdn/shop/articles/Top_10_Trending_Pastry_Cakes_You_Need_to_Try.webp?v=1739364407&width=1920',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 1,
                'category_id' => 9,
                'name' => 'লাচ্ছি',
                'description' => 'তাজা দই থেকে তৈরি মিষ্টি লাচ্ছি, গরমে প্রশান্তিদায়ক পানীয়।',
                'price' => 60,
                'stock_quantity' => 80,
                'image_url' => 'https://i.ytimg.com/vi/A5EXH80NYyY/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCFwcjgmcsz4eWtxMw6dbZvC7rtTQ',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'category_id' => 9,
                'name' => 'বোরহানি',
                'description' => 'পাচন সহায়ক এই মসলাদার পানীয় বিশেষ করে ইফতারে জনপ্রিয়।',
                'price' => 70,
                'stock_quantity' => 65,
                'image_url' => 'https://ayshasrecipe.com/wp-content/uploads/2021/06/borhani-o-borhanir-moshla.jpg',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'category_id' => 9,
                'name' => 'আখের রস',
                'description' => 'তাজা আখ থেকে প্রাপ্ত প্রাকৃতিক মিষ্টির রস, এনার্জি বুস্টার হিসেবে কাজ করে।',
                'price' => 40,
                'stock_quantity' => 120,
                'image_url' => 'https://cf-img-a-in.tosshub.com/lingo/atbn/images/story/202303/thumbnail_joseph_mucira_from_pixabay-sugarcane-5388628_1920-sixteen_nine.jpg?size=948:533',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 4,
                'category_id' => 9,
                'name' => 'নারিকেল পানি',
                'description' => 'প্রাকৃতিক ইলেক্ট্রোলাইট সমৃদ্ধ তাজা নারিকেল পানি, শরীর ঠান্ডা রাখে।',
                'price' => 50,
                'stock_quantity' => 90,
                'image_url' => 'https://res.cloudinary.com/peloton-cycle/image/fetch/f_auto,c_limit,w_3840,q_90/https://images.ctfassets.net/6ilvqec50fal/34IvWHpjsMv8yufOpA8uKK/3bbe4e5cf526caf9d8acdf184a635586/health-benefits-of-coconut-water.jpg',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 5,
                'category_id' => 9,
                'name' => 'ফালুদা',
                'description' => 'গোলাপ ফ্লেভারের এই ঠান্ডা পানীয় গ্রীষ্মকালে বিশেষ জনপ্রিয়।',
                'price' => 80,
                'stock_quantity' => 55,
                'image_url' => 'https://platedfocus.com/wp-content/uploads/2024/10/Plated-Focus-Low-Carb-Falooda-1-500x500.jpg',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 6,
                'category_id' => 9,
                'name' => 'লেবুর শরবত',
                'description' => 'তাজা লেবু ও চিনির তৈরি এই শরবত গরমে শরীরের তাপমাত্রা নিয়ন্ত্রণ করে।',
                'price' => 30,
                'stock_quantity' => 150,
                'image_url' => 'https://images.unsplash.com/photo-1651993737174-6890c1daef5b?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 1,
                'category_id' => 10,
                'name' => 'ফ্রোজেন চিকেন নাগেট',
                'description' => 'ক্রিস্পি চিকেন নাগেট, দ্রুত প্রস্তুত করার জন্য আদর্শ। শিশুদের প্রিয় স্ন্যাক্স।',
                'price' => 350,
                'stock_quantity' => 45,
                'image_url' => 'https://media.istockphoto.com/id/1729802612/photo/delicious-frozen-nugget-in-supermarket.jpg?s=612x612&w=0&k=20&c=M4UZGddIZaRKPvrW0q2t4avqnUNs65nsMAZbFd8MUTA=',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 2,
                'category_id' => 10,
                'name' => 'ফ্রোজেন সমুচা',
                'description' => 'প্রি-ফ্রাইড সমুচা, মাইক্রোওয়েভে গরম করে খেতে পারেন। দ্রুত নাস্তার জন্য উপযুক্ত।',
                'price' => 220,
                'stock_quantity' => 60,
                'image_url' => 'https://tahoora.com/images/thumbs/0001990.jpeg',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 3,
                'category_id' => 10,
                'name' => 'ফ্রোজেন পিজা',
                'description' => 'রেডি-টু-কুক পিজা, ১৫ মিনিটেই প্রস্তুত। বিভিন্ন ফ্লেভারে পাওয়া যায়।',
                'price' => 450,
                'stock_quantity' => 30,
                'image_url' => 'https://www.simplyrecipes.com/thmb/qQQcW-rAPYgtV692kJJdl2gb9QA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Pizza-LEAD-04-25fea854402d4656b910303f07b7299c.jpg',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 4,
                'category_id' => 10,
                'name' => 'ফ্রোজেন ফ্রেঞ্চ ফ্রাই',
                'description' => 'ক্রিস্পি ফ্রেঞ্চ ফ্রাই, কয়েক মিনিটেই প্রস্তুত। বার্গার বা ফাস্ট ফুডের সাথে পরিবেশন করুন।',
                'price' => 180,
                'stock_quantity' => 75,
                'image_url' => 'https://media.istockphoto.com/id/671770262/photo/frozen-french-fries.jpg?s=612x612&w=0&k=20&c=FRqAf1BcdN5AQwnafAX6VeHQsk8-X2QMblqMqtNZR8k=',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 5,
                'category_id' => 10,
                'name' => 'ফ্রোজেন মিক্সড ভেজিটেবল',
                'description' => 'বিভিন্ন ধরনের শাকসবজির মিশ্রণ, রান্নার সময় বাঁচায়। পুষ্টিগুণ সংরক্ষিত।',
                'price' => 120,
                'stock_quantity' => 90,
                'image_url' => 'https://www.healthyfood.com/wp-content/uploads/2020/05/10-ways-with-frozen-vegetables-iStock-182197343.jpg',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'seller_id' => 6,
                'category_id' => 10,
                'name' => 'ফ্রোজেন আইসক্রিম',
                'description' => 'বিভিন্ন ফ্লেভারের ক্রিমি আইসক্রিম, গরমে প্রশান্তিদায়ক ঠান্ডা খাবার।',
                'price' => 280,
                'stock_quantity' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1749863438325-ec3ae343b014?q=80&w=1031&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]


        ]);
    }
}
